---
title: "Homework5 Submission1"
author: "Moyo Odugbemi"
prefer-html: true
subtitle: "https://github.com/modugbe/homework5"
format: 
   pdf: 
     df-print: default
     output-file: "odugbemi-m-hwk5-1"
     output-ext: "pdf"
     header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}
---


```{r results="hide", echo=FALSE, message=FALSE}
#| include: false

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary,
               kableExtra, webshot2, knitr)
```



```{r results="hide", echo=FALSE, message=FALSE}
#| include: false
#| eval: true
 
load("/Users/moyosoreoluwaodugbemi/Econ 470/Homework 5/submission1/Hwk5_workspace.Rdata")
```


\newpage
#Question 1
```{r results="hide", echo=FALSE, message=FALSE}
number1
```

\newpage
#Question 2
The initial increase in self purchase resulted from the establishment of the exchange. The reduction may have been caused by medicaid expansion in states that expanded.

\newpage
#Question 3
```{r results="hide", echo=FALSE, message=FALSE}
number3
```

\newpage
#Question 4
```{r results="hide", echo=FALSE, message=FALSE}
number4
```

\newpage
#Question 5
```{r results="asis", echo=FALSE, message=FALSE, warning=FALSE}
#| echo: false
#| label: Star Rating Count
#| tbl-cap: "Star Rating Counts"

options(knitr.kable.NA = 0)
knitr::kable(number5, 
          booktabs = TRUE) %>%
          kable_styling(latex_options=c("scale_down"))
```

\newpage
#Question 6

```{r results="asis", echo=FALSE, message=FALSE}
number6
```


\newpage
#Question 7 
```{r results="hide", echo=FALSE, message=FALSE}
number7
```



\newpage
#Question 8 
```{r results="hide", echo=FALSE, message=FALSE}
number8
```


\newpage
#Question 9 
```{r results="hide", echo=FALSE, message=FALSE}
number9
```

\newpage
#Question 10
```{r results="hide", echo=FALSE, message=FALSE}
number10
```